name: composer-git-hooks

services:
  appserver:
    type: php:8.1
    via: cli
    xdebug: true
    composer_version: 2

# Add additional tooling
tooling:
  composer:
    service: appserver
  phpcs:
    service: appserver
  phpcbf:
    service: appserver
  phpstan:
    service: appserver